
@baseUrl = http://localhost:8000/api/order
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFjYzNmZmMxZDE2NTdlODYxODlhMTYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDkwMzQyOTEsImV4cCI6MTc1MTYyNjI5MX0.k9kt-_RA1s7XyAwslgf4EVLxWfE6FhPJYjR1x0sowWc
@productId = 681e2fabd99271228561facc

### Crear una orden
POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "items": [
    {
      "product": "6836e7aa3625cb5559a3f0ba",
      "quantity": 2,
      "unit_price": 15
    }
  ],
  "total": 30.00,
  "deliveryMethod": "express",
  "shippingAddress": {
    "street": "Calle Falsa",
    "number": "123",
    "postal": "28080",
    "city": "Madrid",
    "province": "Madrid"
  }
}

### Obtener todas las órdenes del usuario autenticado
GET {{baseUrl}}
Authorization: Bearer {{token}}

### Obtener una orden por ID
GET {{baseUrl}}/682091c8f273578c0634d410
Authorization: Bearer {{token}}

### Actualizar el estado de una orden (admin)
PATCH {{baseUrl}}/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "682091c8f273578c0634d410",
  "state": "sent"
}

### Eliminar una orden (lógica)
DELETE {{baseUrl}}/64fc78a1b60e4100234b9f21
Authorization: Bearer {{token}}
